AWSTemplateFormatVersion: '2010-09-09'
Description: 'InsightSphere Dashboard - Complete Infrastructure Stack'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name (dev, staging, or prod)
  
  ProjectName:
    Type: String
    Default: insightsphere
    Description: Project name used for resource naming
  
  AdminEmail:
    Type: String
    Description: Email address for the admin user
    AllowedPattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$

Conditions:
  IsProduction: !Equals [!Ref EnvironmentName, prod]

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ProjectName}-${EnvironmentName}-users'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
      UserPoolTags:
        Environment: !Ref EnvironmentName
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${ProjectName}-${EnvironmentName}-client'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      RefreshTokenValidity: 30
  
  AdminUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admin
      Description: Administrator users
      UserPoolId: !Ref UserPool
  
  ViewerUserGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: viewer
      Description: Viewer users
      UserPoolId: !Ref UserPool
  
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub '${ProjectName}_${EnvironmentName}_identity'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName
  
  # DynamoDB Tables
  ChatLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${EnvironmentName}-chatlogs'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: conversationId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: byConversation
          KeySchema:
            - AttributeName: conversationId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: byUser
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
  
  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${EnvironmentName}-feedback'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: logId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: byLogId
          KeySchema:
            - AttributeName: logId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: byUser
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
  
  # S3 Bucket for Exports
  ExportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${EnvironmentName}-exports-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: !If [IsProduction, Enabled, Suspended]
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldExports
            Status: Enabled
            ExpirationInDays: 30
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
  
  # IAM Roles
  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${EnvironmentName}-appsync-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt ChatLogTable.Arn
                  - !Sub '${ChatLogTable.Arn}/index/*'
                  - !GetAtt FeedbackTable.Arn
                  - !Sub '${FeedbackTable.Arn}/index/*'
  
  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${EnvironmentName}-authenticated-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource:
                  - arn:aws:dynamodb:us-east-1:327052515912:table/UnityAIAssistantLogs
                  - arn:aws:dynamodb:us-east-1:327052515912:table/userFeedback
                  - arn:aws:dynamodb:us-east-1:327052515912:table/UnityAIAssistantEvalJob
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub '${ExportsBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt ExportsBucket.Arn
  
  UnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${EnvironmentName}-unauthenticated-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: unauthenticated
      Policies:
        - PolicyName: DenyAll
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action: '*'
                Resource: '*'
  
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt AuthenticatedRole.Arn
        unauthenticated: !GetAtt UnauthenticatedRole.Arn
  
  # AppSync GraphQL API
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub '${ProjectName}-${EnvironmentName}-api'
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        UserPoolId: !Ref UserPool
        AwsRegion: !Ref AWS::Region
        DefaultAction: ALLOW
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppSyncLogsRole.Arn
        FieldLogLevel: !If [IsProduction, ERROR, ALL]
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
  
  AppSyncLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs
  
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Definition: |
        type ChatLog {
          id: ID!
          conversationId: String!
          userId: String!
          userMessage: String!
          aiResponse: String!
          timestamp: AWSDateTime!
          metadata: AWSJSON
        }
        
        type Feedback {
          id: ID!
          logId: String!
          userId: String!
          rating: Int!
          comment: String
          timestamp: AWSDateTime!
        }
        
        type Query {
          getChatLog(id: ID!): ChatLog
          listChatLogs(limit: Int, nextToken: String): ChatLogConnection
          getChatLogsByConversation(conversationId: String!, limit: Int, nextToken: String): ChatLogConnection
          getChatLogsByUser(userId: String!, limit: Int, nextToken: String): ChatLogConnection
          getFeedback(id: ID!): Feedback
          listFeedback(limit: Int, nextToken: String): FeedbackConnection
        }
        
        type Mutation {
          createChatLog(input: CreateChatLogInput!): ChatLog
          updateChatLog(input: UpdateChatLogInput!): ChatLog
          deleteChatLog(id: ID!): ChatLog
          createFeedback(input: CreateFeedbackInput!): Feedback
        }
        
        type Subscription {
          onCreateChatLog: ChatLog @aws_subscribe(mutations: ["createChatLog"])
          onCreateFeedback: Feedback @aws_subscribe(mutations: ["createFeedback"])
        }
        
        input CreateChatLogInput {
          conversationId: String!
          userId: String!
          userMessage: String!
          aiResponse: String!
          metadata: AWSJSON
        }
        
        input UpdateChatLogInput {
          id: ID!
          metadata: AWSJSON
        }
        
        input CreateFeedbackInput {
          logId: String!
          userId: String!
          rating: Int!
          comment: String
        }
        
        type ChatLogConnection {
          items: [ChatLog]
          nextToken: String
        }
        
        type FeedbackConnection {
          items: [Feedback]
          nextToken: String
        }
  
  ChatLogDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: ChatLogTable
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      DynamoDBConfig:
        TableName: !Ref ChatLogTable
        AwsRegion: !Ref AWS::Region
  
  FeedbackDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: FeedbackTable
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      DynamoDBConfig:
        TableName: !Ref FeedbackTable
        AwsRegion: !Ref AWS::Region

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Description: Cognito User Pool ID
  
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Description: Cognito User Pool Client ID
  
  IdentityPoolId:
    Value: !Ref IdentityPool
    Description: Cognito Identity Pool ID
  
  GraphQLApiEndpoint:
    Value: !GetAtt GraphQLApi.GraphQLUrl
    Description: AppSync GraphQL API Endpoint
  
  GraphQLApiId:
    Value: !GetAtt GraphQLApi.ApiId
    Description: AppSync GraphQL API ID
  
  ChatLogTableName:
    Value: !Ref ChatLogTable
    Description: DynamoDB ChatLog Table Name
  
  FeedbackTableName:
    Value: !Ref FeedbackTable
    Description: DynamoDB Feedback Table Name
  
  ExportsBucketName:
    Value: !Ref ExportsBucket
    Description: S3 Exports Bucket Name
  
  Region:
    Value: !Ref AWS::Region
    Description: AWS Region
