name: Deploy to EKS

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: swbc-ethos-ai-cluster
  ECR_REPOSITORY: swbc-ethos-ai
  NAMESPACE: swbc-ethos-ai

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run type checking
      run: npm run type-check

    - name: Run tests
      run: npm run test

    - name: Build application
      run: npm run build:prod

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup DynamoDB tables
      run: |
        export AWS_REGION=${{ env.AWS_REGION }}
        export ENVIRONMENT=${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
        node eks-deployment/scripts/setup-dynamodb.js

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Create ECR repository if it doesn't exist
        aws ecr describe-repositories --repository-names $ECR_REPOSITORY || \
        aws ecr create-repository --repository-name $ECR_REPOSITORY

        # Build and push image
        docker build -f eks-deployment/docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        # Also tag as latest for the current branch
        BRANCH_TAG=${{ github.ref == 'refs/heads/main' && 'latest' || 'develop' }}
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Apply namespace
        kubectl apply -f eks-deployment/kubernetes/namespace.yaml

        # Apply ConfigMap and Secret
        kubectl apply -f eks-deployment/kubernetes/configmap.yaml
        kubectl apply -f eks-deployment/kubernetes/secret.yaml

        # Update deployment with new image
        sed "s|ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/swbc-ethos-ai:latest|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" \
          eks-deployment/kubernetes/deployment.yaml | kubectl apply -f -

        # Apply service
        kubectl apply -f eks-deployment/kubernetes/service.yaml

        # Wait for deployment to be ready
        kubectl rollout status deployment/ethos-ai-frontend -n $NAMESPACE --timeout=300s

    - name: Verify deployment
      run: |
        kubectl get pods -n $NAMESPACE
        kubectl get services -n $NAMESPACE
        
        # Check if pods are running
        kubectl wait --for=condition=ready pod -l app=ethos-ai-frontend -n $NAMESPACE --timeout=300s

    - name: Run health check
      run: |
        # Get service endpoint and test health
        kubectl port-forward service/ethos-ai-frontend-service 8080:80 -n $NAMESPACE &
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1
        
        echo "Health check passed!"

  notify:
    needs: [test, build-and-deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify deployment status
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}