#!/bin/bash

# InsightSphere Dashboard - Bash Deployment Script
# This script deploys the complete infrastructure using AWS CLI

set -e

# Configuration
STACK_NAME="insightsphere-dev"
REGION="us-east-1"
ADMIN_EMAIL="${1:-admin@insightsphere.local}"
ENVIRONMENT="dev"
PROJECT_NAME="insightsphere"

echo "============================================"
echo "InsightSphere Dashboard - AWS Deployment"
echo "============================================"
echo ""
echo "Configuration:"
echo "  Stack Name: $STACK_NAME"
echo "  Region: $REGION"
echo "  Admin Email: $ADMIN_EMAIL"
echo "  Environment: $ENVIRONMENT"
echo ""

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    echo "Error: AWS CLI not found"
    exit 1
fi

# Check AWS credentials
echo "Checking AWS credentials..."
if ! aws sts get-caller-identity --region $REGION &> /dev/null; then
    echo "Error: AWS credentials not configured"
    echo "Run: aws configure"
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "AWS Account: $ACCOUNT_ID"
echo ""

# Check if template exists
if [ ! -f "cloudformation/insightsphere-stack.yaml" ]; then
    echo "Error: CloudFormation template not found"
    exit 1
fi

# Confirm deployment
read -p "Do you want to proceed with deployment? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    echo "Deployment cancelled"
    exit 0
fi

echo ""
echo "Creating CloudFormation stack..."
echo "This will take 10-15 minutes..."
echo ""

# Create stack
aws cloudformation create-stack \
    --stack-name $STACK_NAME \
    --template-body file://cloudformation/insightsphere-stack.yaml \
    --parameters \
        ParameterKey=EnvironmentName,ParameterValue=$ENVIRONMENT \
        ParameterKey=ProjectName,ParameterValue=$PROJECT_NAME \
        ParameterKey=AdminEmail,ParameterValue=$ADMIN_EMAIL \
    --capabilities CAPABILITY_NAMED_IAM \
    --region $REGION

if [ $? -eq 0 ]; then
    echo "Stack creation initiated!"
    echo "Waiting for completion..."
    echo ""
    
    # Wait for stack creation
    aws cloudformation wait stack-create-complete \
        --stack-name $STACK_NAME \
        --region $REGION
    
    if [ $? -eq 0 ]; then
        echo ""
        echo "============================================"
        echo "Stack created successfully!"
        echo "============================================"
        echo ""
        
        # Get outputs
        echo "Retrieving stack outputs..."
        OUTPUTS=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --region $REGION \
            --query 'Stacks[0].Outputs')
        
        USER_POOL_ID=$(echo $OUTPUTS | jq -r '.[] | select(.OutputKey=="UserPoolId") | .OutputValue')
        CLIENT_ID=$(echo $OUTPUTS | jq -r '.[] | select(.OutputKey=="UserPoolClientId") | .OutputValue')
        GRAPHQL_ENDPOINT=$(echo $OUTPUTS | jq -r '.[] | select(.OutputKey=="GraphQLApiEndpoint") | .OutputValue')
        BUCKET_NAME=$(echo $OUTPUTS | jq -r '.[] | select(.OutputKey=="ExportsBucketName") | .OutputValue')
        
        echo ""
        echo "AWS Resources:"
        echo "  User Pool ID: $USER_POOL_ID"
        echo "  Client ID: $CLIENT_ID"
        echo "  GraphQL Endpoint: $GRAPHQL_ENDPOINT"
        echo "  S3 Bucket: $BUCKET_NAME"
        echo ""
        
        # Update .env file
        echo "Updating .env file..."
        cat > .env << EOF
# Development Environment Configuration
# Auto-generated by deploy.sh
# Generated: $(date)

# Environment identifier
VITE_ENV=$ENVIRONMENT

# AWS Amplify Configuration
VITE_AWS_REGION=$REGION
VITE_USER_POOL_ID=$USER_POOL_ID
VITE_USER_POOL_CLIENT_ID=$CLIENT_ID
VITE_GRAPHQL_ENDPOINT=$GRAPHQL_ENDPOINT
VITE_S3_BUCKET=$BUCKET_NAME

# API Configuration
VITE_API_TIMEOUT=30000
VITE_API_RETRY_ATTEMPTS=3

# Feature Flags
VITE_ENABLE_ANALYTICS=false
VITE_ENABLE_ERROR_TRACKING=true
VITE_ENABLE_PERFORMANCE_MONITORING=true

# Monitoring
VITE_SENTRY_DSN=
VITE_SENTRY_ENVIRONMENT=$ENVIRONMENT
VITE_SENTRY_TRACES_SAMPLE_RATE=0.1

# Debug Settings
VITE_DEBUG_MODE=true
VITE_LOG_LEVEL=debug

# Performance Settings
VITE_ENABLE_SOURCE_MAPS=true
VITE_BUNDLE_ANALYZER=false
EOF
        
        echo ".env file updated!"
        echo ""
        
        # Create aws-exports.ts
        echo "Creating aws-exports.ts..."
        cat > src/aws-exports.ts << EOF
/**
 * AWS Amplify Configuration
 * Auto-generated by deploy.sh
 */

const awsconfig = {
  aws_project_region: '$REGION',
  aws_cognito_region: '$REGION',
  aws_user_pools_id: '$USER_POOL_ID',
  aws_user_pools_web_client_id: '$CLIENT_ID',
  aws_appsync_graphqlEndpoint: '$GRAPHQL_ENDPOINT',
  aws_appsync_region: '$REGION',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: '$BUCKET_NAME',
  aws_user_files_s3_bucket_region: '$REGION',
};

export default awsconfig;
EOF
        
        echo "aws-exports.ts created!"
        echo ""
        
        # Create admin user
        echo "Creating admin user..."
        aws cognito-idp admin-create-user \
            --user-pool-id $USER_POOL_ID \
            --username admin \
            --user-attributes Name=email,Value=$ADMIN_EMAIL Name=email_verified,Value=true \
            --temporary-password 'TempPass123!' \
            --message-action SUPPRESS \
            --region $REGION 2>/dev/null || echo "User may already exist"
        
        # Add to admin group
        aws cognito-idp admin-add-user-to-group \
            --user-pool-id $USER_POOL_ID \
            --username admin \
            --group-name admin \
            --region $REGION 2>/dev/null || echo "User may already be in group"
        
        echo ""
        echo "============================================"
        echo "Deployment Complete!"
        echo "============================================"
        echo ""
        echo "Next Steps:"
        echo "1. Start the development server:"
        echo "   npm run dev"
        echo ""
        echo "2. Open your browser:"
        echo "   http://localhost:5173"
        echo ""
        echo "3. Sign in with:"
        echo "   Username: admin"
        echo "   Password: TempPass123!"
        echo "   (You'll be prompted to change it)"
        echo ""
        
    else
        echo "Stack creation failed or timed out"
        echo "Check AWS Console for details"
        exit 1
    fi
else
    echo "Failed to initiate stack creation"
    exit 1
fi
