/**
 * AWS Amplify Configuration
 * Auto-generated by CloudFormation deployment
 * Generated: 2024-12-04
 */

const awsconfig = {
  aws_project_region: 'us-east-1',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_gYh3rcIFz',
  aws_user_pools_web_client_id: '6mlu9llcomgp1iokfk3552tvs3',
  aws_cognito_identity_pool_id: 'us-east-1:c4d5c67a-30d9-49ac-bc80-542775e19d9d',
  aws_appsync_graphqlEndpoint: 'https://y7sc7o27czcp3pw6lyib6ma2we.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'insightsphere-dev-exports-327052515912',
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsconfig;
